# Generated by Django 3.2.5 on 2021-08-14 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_rename_user_driver_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
