# Generated by Django 3.2.5 on 2021-07-16 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering', '0003_alter_order_deliverytime'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliveryMethod',
            field=models.CharField(default='TakeAway', max_length=8),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartItems', to='Ordering.order'),
        ),
    ]
