# Generated by Django 3.2.5 on 2021-07-16 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering', '0006_auto_20210716_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
    ]
