# Generated by Django 3.2.5 on 2021-07-17 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering', '0008_auto_20210717_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='Item',
            new_name='item',
        ),
    ]
