# Generated by Django 3.2.5 on 2021-07-18 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering', '0010_auto_20210718_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='deliveryDay',
        ),
        migrations.RemoveField(
            model_name='order',
            name='deliveryMethod',
        ),
        migrations.RemoveField(
            model_name='order',
            name='deliveryTime',
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('deliveryDay', models.CharField(choices=[('Today', 'Today'), ('Tomorrow', 'Tomorrow')], max_length=8)),
                ('deliveryTime', models.TimeField()),
                ('deliveryMethod', models.CharField(max_length=8)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Ordering.order')),
            ],
        ),
    ]
