# Generated by Django 3.2.5 on 2021-07-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering', '0011_auto_20210718_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='description',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='telephone',
            field=models.PositiveIntegerField(default=99999, max_length=99999999),
        ),
    ]
