# Generated by Django 3.2.5 on 2021-07-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering', '0012_auto_20210718_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='telephone',
            field=models.PositiveIntegerField(default=99999),
        ),
    ]
