# Generated by Django 3.2.5 on 2021-07-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering', '0013_alter_orderdetail_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='telephone',
            field=models.PositiveIntegerField(),
        ),
    ]
