# Generated by Django 3.2.5 on 2021-07-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering', '0014_auto_20210719_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='postal_code',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='deliveryTime',
            field=models.TimeField(verbose_name='11.30am'),
        ),
    ]
