# Generated by Django 3.2.5 on 2021-07-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering', '0015_auto_20210719_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='deliveryTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='postal_code',
            field=models.PositiveIntegerField(),
        ),
    ]
