# Generated by Django 3.2.5 on 2021-08-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering', '0019_alter_order_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='address',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='full_address',
            field=models.CharField(default=None, max_length=120),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='deliveryMethod',
            field=models.CharField(choices=[('Delivery', 'Delivery'), ('TakeAway', 'TakeAway')], max_length=8),
        ),
    ]
