# Generated by Django 3.2.5 on 2021-08-05 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Yummy', '0005_alter_restaurantreview_user'),
        ('Ordering', '0021_auto_20210804_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Yummy.restaurant'),
        ),
    ]
