# Generated by Django 3.2.5 on 2021-08-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_blog_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_text',
            field=models.TextField(help_text='Maximum length is 1024', max_length=1024),
        ),
    ]
