# Generated by Django 3.2.5 on 2021-08-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_alter_blog_blog_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='is_approved',
            field=models.BooleanField(default=False, help_text="Only approved blogs show on the 'blogs' page", verbose_name='Approved'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Primary'),
        ),
    ]
