# Generated by Django 3.2.5 on 2021-08-14 09:07

import Blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_auto_20210803_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='If checked: the blog is shown on the main page', verbose_name='Primary'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='picture',
            field=models.ImageField(help_text="Valid extension's are JPG,PNG", upload_to=Blog.models.Upload_path_for_blog, validators=[Blog.models.custom_image_validator]),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(help_text='Maximum length is 16', max_length=16),
        ),
    ]
