# Generated by Django 3.2.5 on 2021-07-16 06:30

import Yummy.models
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True, unique=True)),
                ('restaurant_type', multiselectfield.db.fields.MultiSelectField(choices=[('American', 'American'), ('Chinese', 'Chinese'), ('Hamburger', 'Hamburger'), ('Fish', 'Fish'), ('Mexican', 'Mexican'), ('Pizza', 'Pizza'), ('Sushi', 'Sushi')], default='American', max_length=45)),
                ('postal_code', models.IntegerField(null=True)),
                ('phone_number', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('website_url', models.URLField(null=True)),
                ('delivery_charge', models.IntegerField(null=True)),
                ('logo', models.ImageField(null=True, upload_to=Yummy.models.get_upload_path_for_logo)),
                ('is_delivery', models.BooleanField(default=False)),
                ('is_take_away', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_submit', models.BooleanField(default=False)),
                ('long', models.DecimalField(decimal_places=6, default=51.337888, max_digits=8)),
                ('lat', models.DecimalField(decimal_places=6, default=35.699784, max_digits=8)),
                ('address', models.CharField(default='None', max_length=60)),
                ('city', models.CharField(default='Tehran', max_length=15)),
                ('description', ckeditor.fields.RichTextField(null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('food_quality', models.DecimalField(decimal_places=3, max_digits=4)),
                ('price', models.DecimalField(decimal_places=3, max_digits=4)),
                ('punctuality', models.DecimalField(decimal_places=3, max_digits=4)),
                ('courtesy', models.DecimalField(decimal_places=3, max_digits=4)),
                ('description', models.TextField(max_length=200)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Yummy.restaurant')),
                ('user', models.ForeignKey(default=Yummy.models.Get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=Yummy.models.get_upload_path_for_image)),
                ('restaurant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Yummy.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='OpeningTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=9)),
                ('from_hour', models.TimeField(blank=True, null=True)),
                ('to_hour', models.TimeField(blank=True, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Opening_time', to='Yummy.restaurant')),
            ],
            options={
                'ordering': ('weekday', 'from_hour'),
            },
        ),
    ]
