# Generated by Django 3.2.5 on 2021-07-16 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Yummy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_type',
        ),
    ]
