# Generated by Django 3.2.5 on 2021-08-01 13:28

import Yummy.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Yummy', '0003_auto_20210727_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantreview',
            name='user',
            field=models.ForeignKey(default=Yummy.models.Get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
