# Generated by Django 3.2.5 on 2021-08-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yummy', '0005_alter_restaurantreview_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=35.699784, max_digits=8),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='long',
            field=models.DecimalField(decimal_places=6, default=51.337888, max_digits=8),
        ),
    ]
