# Generated by Django 3.2.5 on 2021-08-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yummy', '0006_auto_20210805_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='delivery_charge',
            field=models.IntegerField(help_text='Just whole numbers are acceptabe.', null=True),
        ),
    ]
