# Generated by Django 3.2.5 on 2021-08-19 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Yummy', '0002_auto_20210819_1225'),
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='menu',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Menu.menu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Yummy.restaurant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Starter', 'Starter'), ('Main course', 'Main course'), ('Beef', 'Beef'), ('Dessert', 'Dessert'), ('Drink', 'Drink')], help_text='Maximum length is 11', max_length=11),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(help_text='Maximum length is 20', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum digit is 999.99'),
        ),
    ]
