# Generated by Django 3.2.5 on 2021-08-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Starter', 'Starter'), ('Main course', 'Main course'), ('Beef', 'Beef'), ('Dessert', 'Dessert'), ('Drink', 'Drink')], help_text='Maximum length is 11', max_length=11),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(help_text='Maximum length is 20', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum digit is 999.99', max_digits=3),
        ),
    ]
