# Generated by Django 3.2.5 on 2021-08-20 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Yummy', '0003_alter_restaurant_is_submit'),
        ('Menu', '0003_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Starter', 'Starter'), ('Main course', 'Main course'), ('Beef', 'Beef'), ('Dessert', 'Dessert'), ('Drink', 'Drink')], max_length=11),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(help_text='Maximum length is 450', max_length=450),
        ),
        migrations.AlterField(
            model_name='item',
            name='menu',
            field=models.ForeignKey(limit_choices_to={'is_submit': True}, on_delete=django.db.models.deletion.CASCADE, to='Menu.menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(limit_choices_to={'is_submit': True}, on_delete=django.db.models.deletion.CASCADE, to='Yummy.restaurant'),
        ),
    ]
