# Generated by Django 3.2.5 on 2021-08-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0006_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum digit is 99.99', max_digits=4),
        ),
    ]
