# Generated by Django 3.2.5 on 2021-08-20 18:00

import Menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0007_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(upload_to=Menu.models.get_upload_path_picture, validators=[Menu.models.custom_image_validator]),
        ),
    ]
